### ISSUE TITLE
Availability of code in Java

### ISSUE THREAD

**Issue by jainritika123** [SimpleNexus/simplecallerid#10]
Hello, 
I am a beginner , i have worked on few projects in java but not kotlin.
Is there any resource that can help me to understand this code in java?

**Comment by jacobmichaelis** [comment]
I'm sorry, I don't have this repo in Java. I performed a basic search on Google to see if there is some sort of conversion, and I think this SO should help: https://stackoverflow.com/questions/34957430/how-to-convert-a-kotlin-source-file-to-a-java-source-file

**Comment by schorschii** [comment]
@jainritika123 I converted it to Java here: https://gist.github.com/schorschii/cfe3b986835e12ae816dc42535e51734
