### ISSUE TITLE
Possible bug: can't see it on Android Q

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [SimpleNexus/simplecallerid#5]
Maybe I'm using the sample incorrectly, but here's what I did:

1. I've deleted a contact from the address book, while copying its phone number.
2. I've added the phone number to the sample app, with some random text for first name and last name, and having only digits for the phone number (because for some reason it didn't allow me otherwise).
3. On the Phone app (of Google), I've disabled spam protection.
4. I've tried to call the number and have it as incoming call.

On both of those, I didn't see what I've entered. 

Tested on Pixel 2 Q beta 6.

Is it possible this will work only on specific Android versions? If so, from which version and to which version? I've noticed the minimal set is 19. Is it true?

**Comment by djohannot** [comment]
same here, i cannot get your sample work. Tried to add the country code, etc. but still not working

**Comment by djohannot** [comment]
I think i figured out why it wasn't working. It seems Samsung has something called "customized services" that blocked the use of providers for the contacts. I tested on a Huwei and worked really well. So @AndroidDeveloperLB i think the issue comes from the device brand, not this sample. If you find how to enable this customized service on Samsung i would be happy to know

**Comment by AndroidDeveloperLB** [comment]
@djohannot But I have Pixel device...
It should be the cleanest of them all..
Maybe this sample works only on old Android versions?
Or maybe it needs an update to handle new ones?

**Comment by YSDC** [comment]
Damn.... but it’s interesting to know that. Maybe you’re right I will check the version of the devices i tried on. I have plenty a work I will try to test on multiple.

If it’s not a brand specific issue, try to look at what changed in the last version. The permissions changed a lot during the last version maybe it’s just something related to this.

**Comment by AndroidDeveloperLB** [comment]
@YSDC Too much has changed on Q.
Too many restrictions, and very bad alternatives and workarounds.
But if this is an official API, I believe it should still work.
I never heard of this behavior, and so I was surprised to see a sample for it. Sadly I couldn't get it to work, and so I asked if it's just me because maybe I don't use the sample right.

**Comment by jacobmichaelis** [comment]
@djohannot I had issues getting this to work on Samsung because of what you said. Do you know if it is possible to turn off "customized services"?
@AndroidDeveloperLB I tested this on my Pixel 2 Android Pie. I have to admit this is a fairly finicky feature and I swear some days I come in to work and it is broken, I hack at it for a day to no avail, sleep on it, come in the next day, and it's magically working again. I linked the Android docs in the ReadME, so maybe play around with the different things mentioned in those and just keep at it.

**Comment by AndroidDeveloperLB** [comment]
@jacobmichaelis Sorry I can't help you on this.

**Comment by jacobmichaelis** [comment]
Oh, I was actually trying to offer my help. I am the one who built this repo and tutorial. I just wanted to say keep at it because even though it is finicky it can work. 👍

**Comment by AndroidDeveloperLB** [comment]
@jacobmichaelis Wait, you mean to say you've fixed it on Android Q ?

**Comment by jacobmichaelis** [comment]
Yes, I have tested it and it works on Pie and Q on my Pixel 2. I have not taken time to test other versions.

**Comment by farmerbb** [comment]
@AndroidDeveloperLB @djohannot Are you making sure to test this using the `callerid` branch (which has the finished implementation) as opposed to the `master` branch (which is intended to be a starting point to the tutorial contained in the readme)?

**Comment by AndroidDeveloperLB** [comment]
@farmerbb Why use a different branch? The entire repository is named "simple caller id" . It's supposed to work fine on the normal one.
Why not put what the repository is supposed to do on the main one?
Is it not in stable state yet?

**Comment by farmerbb** [comment]
The repository is in a stable state.  I do agree though, the way we have the branches set up can be confusing.

@jacobmichaelis any thoughts?  Maybe we should put the pre-tutorial and post-tutorial versions in separate modules just on the `master` branch?

**Comment by AndroidDeveloperLB** [comment]
@farmerbb How could you consider the main branch to be in stable state if you recommend me to try a different branch that has the caller-id working, if the repository is about caller-id...

**Comment by jacobmichaelis** [comment]
@AndroidDeveloperLB The repo was made simply for a tutorial. It is not destined for the Play Store by any means. For this reason, the master branch is the starting point for the tutorial (unfinished) and the callerid branch is the suggested end state (for those too lazy to follow along with the tutorial). The master branch is stable in the sense that it does not crash, but only the callerid branch has any actual caller ID implementation.

**Comment by AndroidDeveloperLB** [comment]
@jacobmichaelis The tutorial is about ... caller-id. The repository name is about caller-id. 
The main branch isn't. Who said anything about the Play Store?
The repository's main branch should be the best one to use when you reach it. How could anyone who want to try the caller-id guess that it needed to select some branch instead of using the normal one?
I can also make a stable branch as the master, make it write "hello world", and put the real one in a different branch. That's how it feels. The main branch doesn't work. It doesn't do anything that it's supposed to do as a caller-id.

Practically no repository does that. All repositories put the main functionality and purpose into the main branch.

**Comment by jacobmichaelis** [comment]
Closing because:
- We were getting a little off topic here. The callerid branch is now the default branch
- Samsung phones seem to not be able to use this.

**Comment by jacobmichaelis** [comment]
Specific issue created for discovery on the Samsung issue here: #6

**Comment by AndroidDeveloperLB** [comment]
So, downvote and then agreeing on what I said by setting the default branch the caller-id one...
I don't get it. 
Anyway, thanks.
I tested on emulator and seems it works

**Comment by jacobmichaelis** [comment]
I'm glad it worked out for you. Thank you for all of your input. (Also, I didn't downvote, but I am shocked by how many people were following this thread!)

**Comment by AndroidDeveloperLB** [comment]
@jacobmichaelis And in just such a short time!
You are famous!

I wish to know now more about this, so I asked here:

https://github.com/SimpleNexus/simplecallerid/issues/7
