### ISSUE TITLE
Known Issue Regarding Samsung Phones

### ISSUE THREAD

**Issue by jacobmichaelis** [SimpleNexus/simplecallerid#6]
Samsung phones seem to be unable to use this caller ID feature. This issue thread will be used to talk about potential solutions to that.

**Comment by schorschii** [comment]
A Samsung mod said in [this forum thread](https://eu.community.samsung.com/t5/applications-mobiles-services/request-contactdirectory-providers-in-samsung-phone-app/td-p/4742886) that they have no plans to implement this feature in the Samsung Phone App.
